language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

notifications:
    irc:
        channels:
            - "chat.freenode.net#exobrain"
        on_success: change
        on_failure: always
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"

before_install:
    # This line should try to match what's in our README.md
    - sudo apt-get install libzmq3-dev libexpat-dev libnet-ssleay-perl libnet-libidn-perl libcrypt-ssleay-perl cpanminus make liblocal-lib-perl

install:

    # ZMQ requires us to specify at build-time what back-end
    # we'll use. Travis comes with ZMQ3 pre-installed.
    - export PERL_ZMQ_BACKEND=ZMQ::LibZMQ3

    - cpanm --notest --skip-satisfied Dist::Zilla

    # SMS::Send seems to have issues with MakeMaker shipped with
    # virgin 5.16. So start up upgrading MakeMaker.
    # See miyagawa/cpanminus#291 for details

    - cpanm --notest ExtUtils::MakeMaker

    # Current versions of Dist::Zilla need Perl 5.016 or newer
    # but for this distribution travis Dist::Zilla works but 
    # needs Test::TCP installed on Perls 5.014 or older

    - cpanm --notest Test::TCP

    - dzil authordeps         | cpanm --notest --skip-satisfied
    - dzil listdeps --author  | cpanm --notest --skip-satisfied

script:
    - dzil test --all
