language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

branches:
    only:
        - /^build/

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libzmq3-dev libexpat-dev libnet-ssleay-perl libnet-libidn-perl libcrypt-ssleay-perl make liblocal-lib-perl

before_script:
    - cp docs/example.exobrainrc ~/.exobrainrc

script: prove -lr t/
