package App::Exobrain;
use v5.010;
use strict;
use warnings;
use autodie;
use Moose;

# ABSTRACT: Bloop de bloop blah

# VERSION: Generated by DZP::OurPkg:Version

use App::Exobrain::Bus;
use App::Exobrain::Message;

has 'config' => (
    is => 'ro',
    isa => 'App::Exobrain::Config',
    builder => '_build_config',
);

sub _build_config {
    return App::Exobrain::Config->new;
};

=for Pod::Coverage BUILD DEMOLISH

=cut

1;
